### ISSUE TITLE
Bug with complex components names

### ISSUE THREAD

**Issue by GoalVolant** [thesourcerer8/altium2kicad#124]
Thanks for this very usefull work.

I got an error linked to the components naming when I'm using "sheet symbols" in Altium. For example I name a component ='U'+part_idx+3, so that the component of the first sheet is named U13, the one on the second sheet U23, etc... 

I get this error when trying to open the .kicad_pcb : 
![image](https://user-images.githubusercontent.com/101322586/157627744-f7422c03-4320-476e-bea3-11eefa0d03dd.png)

The line 792 of this file is : 
![image](https://user-images.githubusercontent.com/101322586/157627831-843f8d86-eae6-4505-945f-d7a9322f1a6d.png)

that made me think this component naming is the problem. Do you have an idea how to solve this ?

**Comment by thesourcerer8** [comment]
Please provide a demo-file, which I can use for testing/developing.

**Comment by thesourcerer8** [comment]
I just tried the new Altium Importer that has been integrated into Kicad itself (one in PcbNew and on in EESchema, to be found in "File -> Import -> Non-KiCad Files", and the results are much better than altium2kicad, so I would suggest to you use the KiCad integrated importer yourself instead of altium2kicad. If it works for you, please close this issue. If it doesn't work for you, please let me know.

**Comment by GoalVolant** [comment]
Indeed Kicad 7.0.0 provides a very nice importer ! Thanks for the support.
