### ISSUE TITLE
 no unpacked PcbDoc files found

### ISSUE THREAD

**Issue by usmG** [thesourcerer8/altium2kicad#23]
Hello i have used online altium to kicad converter 
I am  getting the same file for .schdoc and .pcbdoc in converted zip file
below is the conversion log 
please help i confused what is problem
version of altium file that need to be taken care or any version can be converted ?

Archive:  db/249.zip
   creating: db/249/test/
  inflating: db/249/test/SMPS.SchDoc  
  inflating: db/249/test/SMPS.PcbDoc  
Done.
No unpacked .PcbDoc documents found. Trying to unpack it:
Done.
There were no unpacked PcbDoc files found.

**Comment by thesourcerer8** [comment]
Please move them out of the test directory, just put them directly into a .zip file. I will try to update the service later to improve subdirectory handling.

**Comment by usmG** [comment]
it i working , but the pads are missing , in entire board i can see only one pad.

Thank's for your job.

**Comment by thesourcerer8** [comment]
I changed it now to remove the subdirectories from the zip files, and I updated it to the newest version, it seems I forgot to deploy the newest version. Please try again now.

**Comment by thesourcerer8** [comment]
The pad handling might be improved now, please try again.

**Comment by DreV96** [comment]
<img width="640" alt="screen shot 2018-03-14 at 9 53 20 am" src="https://user-images.githubusercontent.com/37373340/37406477-9f9ab3de-276d-11e8-9337-ea28b2429e3d.png">

I get the same problem. When I use the altium2kicad converter it automatically downloads a .zipfile without any .pro files in it.

**Comment by thesourcerer8** [comment]
The ZIP file you have uploaded contains only Gerber files, no Altium Design files.
You can open Gerber Files in GerbView, which is part of KiCad. When you have opened them in GerbView you can convert them to a .kicad_pcb , and then continue with PcbNew to work on them, but the Gerber files do not contain all the information that was in the Design files, so the preferred way is to convert .PcbDoc design files instead of Gerber files.
