### ISSUE TITLE
Schematics not converted

### ISSUE THREAD

**Issue by manuvn** [thesourcerer8/altium2kicad#48]
Hi
I am trying to convert the opalkelly breakout board altium designer files to kicad. The tools appears to have failed to convert the schematic files. I am attaching all the relevant documents.

Can you please take a look?
Thank you!

[BRK7305.zip](https://github.com/thesourcerer8/altium2kicad/files/2252233/BRK7305.zip)
[altium2kicad.zip](https://github.com/thesourcerer8/altium2kicad/files/2252230/altium2kicad.zip)

**Comment by thesourcerer8** [comment]
The file was not converted due to uppercase/lowercase filenames, I have fixed the case-sensitivity in the converter now, please try again. And by the way, if you add the logo.jpg into the .zip file, then it would be converted too. (Unfortunately Altium does not store the jpg files in the schematics, so they often get lost.)
